/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['configuration/index.js']) {
  _$jscoverage['configuration/index.js'] = [];
  _$jscoverage['configuration/index.js'][1] = 0;
  _$jscoverage['configuration/index.js'][3] = 0;
  _$jscoverage['configuration/index.js'][4] = 0;
  _$jscoverage['configuration/index.js'][5] = 0;
  _$jscoverage['configuration/index.js'][6] = 0;
  _$jscoverage['configuration/index.js'][7] = 0;
  _$jscoverage['configuration/index.js'][10] = 0;
  _$jscoverage['configuration/index.js'][11] = 0;
  _$jscoverage['configuration/index.js'][14] = 0;
}
_$jscoverage['configuration/index.js'][1]++;
var nconf = require("nconf");
_$jscoverage['configuration/index.js'][3]++;
function Config() {
  _$jscoverage['configuration/index.js'][4]++;
  nconf.argv().env("_");
  _$jscoverage['configuration/index.js'][5]++;
  var environment = nconf.get("NODE:ENV") || "development";
  _$jscoverage['configuration/index.js'][6]++;
  nconf.file(environment, "config/" + environment + ".json");
  _$jscoverage['configuration/index.js'][7]++;
  nconf.file("default", "config/default.json");
}
_$jscoverage['configuration/index.js'][10]++;
Config.prototype.get = (function (key) {
  _$jscoverage['configuration/index.js'][11]++;
  return nconf.get(key);
});
_$jscoverage['configuration/index.js'][14]++;
module.exports = new Config();
_$jscoverage['configuration/index.js'].source = ["var nconf = require('nconf');","","function Config(){","  nconf.argv().env(\"_\");","  var environment = nconf.get(\"NODE:ENV\") || \"development\";","  nconf.file(environment, \"config/\" + environment + \".json\");","  nconf.file(\"default\", \"config/default.json\");","}","","Config.prototype.get = function(key) {","  return nconf.get(key)","};","","module.exports = new Config();"];
