/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['routes/index.js']) {
  _$jscoverage['routes/index.js'] = [];
  _$jscoverage['routes/index.js'][1] = 0;
  _$jscoverage['routes/index.js'][2] = 0;
}
_$jscoverage['routes/index.js'][1]++;
exports.heartbeat = (function (req, res) {
  _$jscoverage['routes/index.js'][2]++;
  res.json(200, "OK");
});
_$jscoverage['routes/index.js'].source = ["exports.heartbeat = function(req, res){","  res.json(200, 'OK');","};"];
