/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['middleware/notFound.js']) {
  _$jscoverage['middleware/notFound.js'] = [];
  _$jscoverage['middleware/notFound.js'][1] = 0;
  _$jscoverage['middleware/notFound.js'][3] = 0;
  _$jscoverage['middleware/notFound.js'][4] = 0;
  _$jscoverage['middleware/notFound.js'][5] = 0;
}
_$jscoverage['middleware/notFound.js'][1]++;
var logger = require("../logger");
_$jscoverage['middleware/notFound.js'][3]++;
exports.index = (function (req, res, next) {
  _$jscoverage['middleware/notFound.js'][4]++;
  logger.error("Not Found");
  _$jscoverage['middleware/notFound.js'][5]++;
  res.json(404, "Not Found.");
});
_$jscoverage['middleware/notFound.js'].source = ["var logger = require(\"../logger\")","","exports.index = function(req, res, next){","  logger.error('Not Found');","  res.json(404, 'Not Found.');","};"];
